name = "Measurements"
uuid = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
authors = ["Mosè Giordano <mose@gnu.org>"]
version = "2.14.1"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
BaseType = "7fbed51b-1ef5-4d67-9085-a4a9b26f478c"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
MeasurementsBaseTypeExt = "BaseType"
MeasurementsJunoExt = "Juno"
MeasurementsMakieExt = "Makie"
MeasurementsRecipesBaseExt = "RecipesBase"
MeasurementsSpecialFunctionsExt = "SpecialFunctions"
MeasurementsUnitfulExt = "Unitful"

[compat]
BaseType = "0.2"
Calculus = "0.4.1, 0.5"
Juno = "0.8"
LinearAlgebra = "<0.0.1, 1"
Makie = "0.21, 0.22, 0.23, 0.24, 0.25"
Printf = "<0.0.1, 1"
RecipesBase = "0.6.0, 0.7, 0.8, 1.0"
SpecialFunctions = "0.8, 1, 2"
Unitful = "1"
julia = "1.10"
